### ISSUE TITLE
Crear la vista search

### ISSUE THREAD

**Issue by vijoin** [BachacoVE/tools_helpdesk#5]
Definir la vista search con:

**Agrupaciones:**
- Por organización
- Por Solicitante
- Aplicación
- Módulo
- Operación
- Categoría de Incidencia
- Tipo de Incidencia

**Filtros:**
- No resueltos (por defecto)
- Día actual
- más de 1 día
- más de 3 días

**Comment by keiverobles** [comment]
Hola Victor, te puedo ayudar con alguno de estos Issues, pero me gustaría que cambiaras las listas 'bulleted' a listas 'task', para ir marcando las que estén listas.
